### ISSUE TITLE
Not working on plain ESXi

### ISSUE THREAD

**Issue by ipsecguy** [rverchere/vmware_exporter#4] opened 2017-06-17 10:48 UTC
Hi,

when running against plain ESXi it fails. Not being a python/vmware expert, this might be due to the pyvmomi not working with ESXi or some (missing?) out of bound checks - I suspect ESXi is exposing other (or limited if I recall) performance measurements.

Andreas
```
/vmware_exporter.py
[2017-06-17 10:40:22.423793+00:00] Start collecting vcenter metrics
Traceback (most recent call last):
  File "./vmware_exporter.py", line 352, in <module>
    REGISTRY.register(VMWareVCenterCollector())
  File "/usr/local/lib/python2.7/dist-packages/prometheus_client/core.py", line 50, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python2.7/dist-packages/prometheus_client/core.py", line 86, in _get_names
    for metric in desc_func():
  File "./vmware_exporter.py", line 134, in collect
    self._vmware_get_vms(content, metrics, counter_info)
  File "./vmware_exporter.py", line 315, in _vmware_get_vms
    float(sum(result[0].value[0].value)))
IndexError: list index out of range
```

**Comment by rverchere** [comment] 2017-06-19 12:42
Hello,

Do you have some VMs up and running on that host?
Can you also tell me which version of ESXi you're running?

I cannot reproduce - yet -the issue with my hosts, I'll add more python checks.

**Comment by is4it-lab** [comment] 2017-06-22 10:42
Hi,

I receive exactly the same error messages when connecting to a vcenter server (6.5 - Appliance)

Robert

**Comment by rverchere** [comment] 2017-06-22 12:18
Hi,

@is4it-lab, can you comment line 134 (`self._vmware_get_vms(content, metrics, counter_info)`) and check if you still have issues?
I'll check deeper the VM metrics retrieval.
Can you also provide me your environment ?
- OS
- Python version
- pyvmomi module version
- prometheus python module version

Thanks,

**Comment by is4it-lab** [comment] 2017-06-22 12:31
Hi,

the script works fine with the change.

my environment:

OS: Debian GNU/Linux 8 (jessie)
Python version: Python 2.7.9
pyvmomi module version: pyvmomi-6.5-py2.7
prometheus python module version: prometheus_client-0.0.19


best regards
Robert

**Comment by rverchere** [comment] 2017-06-22 12:35
Ok but you will not have the vm metrics. I'll take a look.

**Comment by is4it-lab** [comment] 2017-06-22 12:43
There are some metrics:

host, datastore but no vm's


```
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 177471488.0
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 51806208.0
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1498134116.04
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 29.63
...
# HELP vmware_host_cpu_max VMWare Host CPU max availability in Mhz
# TYPE vmware_host_cpu_max gauge
vmware_host_cpu_max{host_name="esx2.testlab.local"} 22788.0
vmware_host_cpu_max{host_name="esx1.testlab.local"} 28800.0
vmware_host_cpu_max{host_name="esx3.testlab.local"} 24000.0
vmware_host_cpu_max{host_name="esx4.testlab.local"} 9576.0
# HELP vmware_host_cpu_usage VMWare Host CPU usage in Mhz
# TYPE vmware_host_cpu_usage gauge
vmware_host_cpu_usage{host_name="esx2.testlab.local"} 5993.0
vmware_host_cpu_usage{host_name="esx1.testlab.local"} 5294.0
vmware_host_cpu_usage{host_name="esx3.testlab.local"} 8694.0
vmware_host_cpu_usage{host_name="esx4.testlab.local"} 115.0
```

**Comment by wtip** [comment] 2017-06-28 00:41
I just tried the exporter against an ESXi 6.5 host (not connected to vcenter) and it's showing me vmware_vm_* metrics for all of my VMs. So as far as I can tell it's working for me.

**Comment by ipsecguy** [comment] 2017-06-29 19:37
Hi,

I am gettng metrics for my VMs now with the current version of the exporter, thanks for the fix! 

vmware_vm_boot_timestamp_seconds
vmware_vm_cpu_usage_average
vmware_vm_disk_read_average
vmware_vm_disk_write_average
vmware_vm_disk_usage_average
vmware_vm_power_state
vmware_vm_snapshot_timestamp_seconds
vmware_vm_snapshots

I am still getting error messages in the logs, however:

Error! Cannot get vm metrics, details:
  (vim.PerformanceManager.EntityMetricBase) []

Andreas

**Comment by rverchere** [comment] 2017-06-30 07:04
Hi,

OK, I get the same issue now with VM that are not managed by my vcenter anymore.
I just changed the error message in commit b0c771ff97085b57d2693f6e8ff698b9dc8054ea to see metrics and vm_name when having this error.

I guess I can close this issue now.

**Closed as completed by rverchere** 2017-06-30 07:04 UTC
